# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines bellow are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
  - id: "drafts"
    dir: "./cmd/drafts"
    binary: "drafts"
    goos:
      - "darwin"
    goarch:
      - "amd64"
      - "arm64"

  - id: "drafts-callback-handler"
    env:
      - CGO_ENABLED=1
    dir: "./cmd/drafts-callback-handler"
    binary: "drafts-callback-handler"
    goos:
      - "darwin"
    goarch:
      - "amd64"
      - "arm64"
    hooks:
      post: build/drafts-callback-handler/package-app.sh

archives:
  - id: drafts
    builds:
      - drafts
    name_template: >-
      drafts-
      {{- if eq .Arch "amd64" }}intel
      {{- else }}arm{{ end }}
  - id: "drafts-callback-handler"
    builds:
      - "drafts-callback-handler"
    name_template: >-
      drafts-callback-handler-
      {{- if eq .Arch "amd64" }}intel
      {{- else }}arm{{ end }}
    files:
      - src: "drafts-callback-handler.zip"
        dst: "Drafts Callback Handler.zip"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - ids:
      - "drafts"
    homepage: "https://example.com/"
    license: "MIT"
    repository:
      owner: your_github_username
      name: your_homebrew_tap_repository
