#!/usr/bin/env bash

ln_safe() {
	test -e "$2" || ln -s "$1" "$2"
}

(cd cmd/drafts-callback-handler && go build -o "Drafts Callback Handler.app/Contents/MacOS/Drafts Callback Handler")
ln_safe "$PWD/cmd/drafts-callback-handler/Drafts Callback Handler.app" "/Applications/Drafts Callback Handler.app"
(cd cmd/drafts && go build)
ln_safe "$PWD/cmd/drafts/drafts" "/usr/local/bin/drafts"
